name: Daily PDF Download

on:
  schedule:
    - cron: '0 11 * * *'     # every day at 4:30 IST
  workflow_dispatch:         # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run the download script
        run: python daily_pdf.py

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: rainfall-pdf
          path: C:\IMD_Rainfall_PDFs\*.pdf
  
